[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "graphscii"
version = "0.1.0"
description = "Pure Python graph visualization in ASCII, no external dependencies* (*except NetworkX)"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Scott VR", email = "scottvr@gmail.com" }
]
dependencies = [
    "networkx>=2.6.0",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing :: Markup",
]

[project.urls]
Homepage = "https://github.com/scottvr/graphscii"
Repository = "https://github.com/scottvr/graphscii.git"
Issues = "https://github.com/scottvr/graphscii/issues"
[tool.hatch.build.targets.wheel]
packages = ["src/graphscii"]